### ISSUE TITLE
"UWP" apps (for Hololens) are not supported

### ISSUE THREAD

**Issue by ronjkarr** [watson-developer-cloud/unity-sdk#173]
Creating a Unity app for the Microsoft Hololens requires the "Windows Store" platform, along with the "Universal 10" SDK (UWP).  However, the UWP is a subset of the full .Net api -- the UWP api does not support old .Net apis.   The Watson Unity SDK uses archaic APIs which generates many build errors when trying to build a Hololens app.  For example, the SDK uses the old BeginRead, BeginWrite, etc. apis for async operations instead of the newer .Net async model.   Also, the old SerializationInfo class is not supported in UWP.

Please modify the SDK to use apis supported by UWP.

**Comment by mediumTaj** [comment]
Are you trying to use any particular services? We have a Watson .NET SDK written in .NET Platform Standard partially completed.

**Comment by ronjkarr** [comment]
I'm starting with SpeechToText, but expect to use others as well.   Thanks

**Comment by mediumTaj** [comment]
Pointed to .NET Standard SDK to try. Closing for now.

**Comment by FricoRico** [comment]
I am still running into the same problems as ronjkarr. I wish to use TTS from the Watson SDK, it works flawlessly in editor but I can't compile. I worked my way around build errors from WebsocketSharp by compiling it into a DLL and using that instead of the loose files.

Sadly I wasn't able to do the same for the entire Watson Unity SDK. How to fix building for UWP/HoloLens?

**Comment by mediumTaj** [comment]
Hi @FricoRico,
Because of different .NET versions, the Watson Unity SDK does not support .NET development. We are developing a .NET Standard SDK that you should be able to use. It is still in development stage and will move to the Watson Developer Cloud eventually but you can give it a try here:

https://github.com/atilatosta/dotnet-standard-sdk/tree/development

**Comment by DenzoNL** [comment]
@mediumTaj I'd like to use Visual Recognition in Unity in combination with the HoloLens. Would you suggest waiting for the feature to appear in the new .NET Standard SDK or am I better off writing my own implementation for that API. I only need to subit images and retrieve the results from Watson, nothing more.

**Comment by mediumTaj** [comment]
@DenzoNL : @eusebiu has a pull request submitted updating some third party plugins and ifdef'ing some AOT code. Can you please try it out? Let me know how it goes!

https://github.com/eusebiu/unity-sdk/tree/WSA_Support

**Comment by gandhirushabh2311** [comment]
Hi,
Can you please update on whether the above pull request worked? Alternatively is there any other way by which I can use IBM Watson in my Windows Store App?

**Comment by mediumTaj** [comment]
Currently the branch is being refactored. You can follow the progress in the `feature-config-refactor` branch. This will be a major release and will remove higher level widget functionality. It looks like all of the changes in the wsa branch were updating 3rd party plugins. Can you try this branch out? Additionally, follow the instructions eusebiu wrote in his branch

>+In order to build the player for Holographic applications, you have to change the Scripting backend (in File->Build Settings->Player settings) to IL2CPP.

**Comment by DenzoNL** [comment]
Unfortunately I can no longer test this as I don't have access to the HoloLens any more.

**Comment by mediumTaj** [comment]
Thank you @HaraldHeide . Can you also try the hololens with the `feature-config-refactor` branch on this repo as well?

**Comment by HaraldHeide** [comment]
DUe to other things at work i had to postpone until newxtweek with further testing I'm afraid sorry

**Comment by jsmith09** [comment]
What has happened with .NET support for Watson Unity sdk since the last post? I am having issues with building projects with hololens toolkit without using .NET scripting backend.

**Comment by mediumTaj** [comment]
@jsmith09 There is a [PR](https://github.com/watson-developer-cloud/unity-sdk/pull/256) open for this. I'm still trying to find some time this week to review it. Can you pull [this version](https://github.com/kimberlysiva/unity-sdk) down and try it out? Please let me know what you think.

**Comment by jsmith09** [comment]
Do you have instructions to make a unity package of this version?

**Comment by mediumTaj** [comment]
@jsmith09 You should be able to download the repository and add it to your Assets directory in your project.

**Comment by jsmith09** [comment]
![image](https://user-images.githubusercontent.com/10263886/32008298-e1b8ef7c-b979-11e7-9eac-0a06575b2572.png)
I tried to build it with .NET and got these build errors.

**Comment by mediumTaj** [comment]
@jsmith09 Can you please @kimberlysiva 's fork? She has a PR submitted but I haven't had a chance to try it out yet.

https://github.com/watson-developer-cloud/unity-sdk/pull/256

**Comment by kimberlysiva** [comment]
@jsmith09 It looks like you have the Unity Speech-To-Text sample in the project? That's where those errors are coming from. Their sample probably isn't going to compile for Hololens.

https://bitbucket.org/Unity-Technologies/speech-to-text

**Comment by jsmith09** [comment]
@mediumTaj @kimberlysiva after removal of the Unity speech to text, there are no build errors.

**Comment by kimberlysiva** [comment]
@jsmith09 Great! Have you had a chance to test anything? I'm using Speech-to-Text and Conversation on Hololens with success. Let me know how your experience goes, I can help troubleshoot if needed.

**Comment by jsmith09** [comment]
No. Unfortunately, I am having issues with building in VS 2017 with .csprog errors.

**Comment by kimberlysiva** [comment]
@jsmith09 I use VS 2017 as well, so that should be fine. Make sure you can get a simple Hololens project running first. The build process is a bit of a mess right now, very dependent on your OS/Unity/Toolkit versions. The HoloDevelopers slack group is a great place to get these issues sorted out.

If you can deploy a simple project with success but the Watson code is causing errors, please let me know what Unity version you're using and share the full errors. Thanks!

**Comment by jsmith09** [comment]
@kimberlysiva when will the stable version with Unity Watson with the .NET fix be released?

**Comment by kimberlysiva** [comment]
@jsmith09 That's not up to me, I don't work here :) I've create this pull request because I'm interested in using Watson on Hololens as well! But I think we need more people testing it before it can make its way to the main repo.

It should work right now, but if you're seeing errors please let me know (I'm not sure what ".csprog errors" means without more info). I'm testing with Unity 2017.1.0f3. What are you using?

**Comment by mediumTaj** [comment]
@jsmith09 yes testing is what we need for sure. I would like to get this in before the push to the Unity Asset store if possible. Time is kinda short for me though!

**Comment by jsmith09** [comment]
Ok. Thanks for the information @mediumTaj. @kimberlysiva I am using Unity 2017.1.2.

**Comment by kimberlysiva** [comment]
@mediumTaj @jsmith09 I just added a unity package to the PR that has a Hololens-friendly sample scene for streaming speech-to-text. It also has further instructions for setup.

https://github.com/watson-developer-cloud/unity-sdk/pull/256#issuecomment-339780759

I'm going to share this on the HoloDevelopers Slack to see if we can get more testers.

**Comment by mediumTaj** [comment]
Awesome, thanks @kimberlysiva !
