### ISSUE TITLE
RESTConnector issues 

### ISSUE THREAD

**Issue by afaisma** [watson-developer-cloud/unity-sdk#196]
-  If the same GET request is submitted twice, the return callback is called the second time without errors but with no data.
 -  The RESTConnector.Response does not contain the details about the problem: the Error field is empty and the Success field equals True.
-    In our app we were trying to use multiple pairs of username/password for DP authentication. In the log files (on the server side) we observed incorrect value of 'UserId' field in the header added by Datapower. UserId value for the next request (initiated with different username/password) was identical to UserId value corresponding to the previous request . Perhaps RestController caches the username/password between requests

**Comment by mediumTaj** [comment]
Is there any way I can get access to the project to take a look?

I do not see GET requests being submitted twice in the base sdk. Which service are you using where it is called twice?

If success is returned on from the REST call, the call was made successfully to the service. Which service are you getting an error from so I can take a look.
 
As far as credentials go, the SDK wasn't built with changing users in mind since it's a Watson SDK and users will typically only have one instance of each service. You would have to change the credentials in the Credential list in Config.cs. This is where each request looks for the credentials.
