### ISSUE TITLE
Transition to UnityWebRequest

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#284]
Move from using WWW to UnityWebRequest for REST calls.

- [x] Remove all WWW and use UnityWebRequest
- [x] Implement PUT method
- [x] Transition DELETE to UnityWebRequest
- [x] Abstract PUT operations to all services. Add tests.
- [x] Ensure we are throwing errors

**Comment by mediumTaj** [comment]
Transitioned DELETE to UnityWebRequest because of failing integration tests here https://github.com/watson-developer-cloud/unity-sdk/pull/286

Still need to handle the rest

**Comment by aestiff** [comment]
Hey I just noticed this issue; FWIW, I've had firewall issues with my app due to the Unity HTTP methods not being proxy-aware. I haven't looked into it deeply, but I hear that the web requests in the standard library implement this, although I'm sure they're not as clean to use. This is really a Unity issue, but if you're working around it anyway, I thought you might like to be aware of it.

**Comment by mediumTaj** [comment]
Thanks @aestiff - from what I can tell even `UnityWebRequest` cannot connect via proxy

https://stackoverflow.com/questions/53213037/rest-connection-using-unitywebrequest-via-proxy/53214048

The team at Unity has confirmed this. I'm trying to find a workaround - if you have any ideas let me know.

**Comment by mediumTaj** [comment]
Complete - All `WWW` has been transitioned to `UnityWebRequest`
