### ISSUE TITLE
Watson 'Speech to text' not recognizing microphone input properly

### ISSUE THREAD

**Issue by satishkumar** [watson-developer-cloud/unity-sdk#398]
Iam using Unity SDK provided for IBM Watson services. I try to use 'ExampleStreaming.cs' sample provided for speech to text recognition. I test the app in unity editor.

This sample uses Microphone as audio input and gets results for voice input from the user. However, when I use microphone as input, the transcribed results are far from being correct. When I say "Create a black box", the results are inappropriate, with the word results being completely irrelevant to input.

When I use pre-recorded voice clips, the output is perfect. Does the service perform incorrectly for Indian accent?. What is the reason for poor microphone input recognition?

The docs say: "In general, the service is sensitive to background noise. For instance, engine noise, working devices, street noise, and talking can significantly reduce accuracy. In addition, the microphones that are typically installed on mobile devices and tablets are often inadequate. The service performs best when professional microphones are used to capture audio with better quality."

I use Logitech headset mic as input source.
BTW, Watson services have been quite valuable in getting things up and running quickly. Thanks so much for this.

**Comment by mediumTaj** [comment]
Hi @satishkumar The standard model of Speech to Text may not be able to accurately transcribe accents 100% of the time. You can try to create a custom language model to help with this:

https://www.ibm.com/blogs/watson/2016/09/build-custom-language-model-convert-unique-speech-text/
https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#custom-language-models-api

Closing this since it is not an issue with the SDK.
