### ISSUE TITLE
Assistant Service MessageResponse object empty 

### ISSUE THREAD

**Issue by anthonyherveHCS** [watson-developer-cloud/unity-sdk#419]
Hello, 
It seems that the "MessageResponse" object returned by the "Message" service callback is always empty (unlike the Dictionary<string, object> object).
The consequence of this is that we can't reuse the context in the next "Message" request.

Thank you

**Comment by mediumTaj** [comment]
Hi @anthonyherveHCS 
I'm looking at the tests and the object seems to be populating. Can you make sure the return type is `object` rather than `MessageResponse`? We need to keep this dynamic since the context can vary.

You can look in the tests to see how we structure the callback to parse out data
```
https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Scripts/UnitTests/TestAssistantCF.cs#L712-L753
```

Closing this for now but please feel free to reopen if you are still having issues.
