### ISSUE TITLE
Universal Windows Platform - Won't build

### ISSUE THREAD

**Issue by StavEW** [watson-developer-cloud/unity-sdk#665]
Hi,

Whenever I try building on UWP, I get 195 errors. 
Didn't had this problem on IOS, OSX, Standalone PC and Android.

Watson (4.8.0)
SDKCore (1.2.1)
Unity (2019.4.10f)

I know there's a Watson (5.0.0) version, but the errors are from the SDKCore (and there is no newer version for it)

Thanks!

**Comment by SrNeper** [comment]
Hello StavEW

I Hope you managed to solve your problem because I have a similar problem and maybe you can help me.

I had create a new project in Unity(2020.3), to test the Watson SDK 5.0 updates and see if I could use it to update a project I developed with 3.4

1. Upon opening it, I followed the step-by-step and updated NetFramework to 4x

2. I created a folder for Watson and threw the unzipped sdk and core in there. But when it shuts down it gets 99+ errors involving Newtonsoft.Json.dll

So I opened his Inspector and selected all the fields that were in "Select platforms for plugin" and with that I only got 1 error:

"Microsoft(R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2001: Source file 'C:\Users\....\WatsonProject\Watson SDK 5.1\SDK' could not be found.
error CS2001: Source file 'C:\Users\....\WatsonProject\Watson SDK 5.1\5.1/unity-sdk-core-1.2.4/Plugins/websocket-sharp.dll' could not be found.
error CS2001: Source file 'C:\Users\....\WatsonProject\Watson SDK 5.1\5.1/unity-sdk-core-1.2.4/ThirdParty/JsonDotNet/AOT/Newtonsoft.Json.dll' could not be found .
error CS2001: Source file 'C:\Users\....\WatsonProject\Watson SDK 5.1\5.1/unity-sdk-core-1.2.4/ThirdParty/JsonDotNet/Windows/Newtonsoft.Json.dll' could not be found .
error CS2001: Source file 'C:\Users\....\WatsonProject\Watson SDK 5.1\5.1/unity-sdk-core-1.2.4/ThirdParty/JsonDotNet/Standalone/Newtonsoft.Json.dll' could not be found ."

Any idea how I can solve this problem? Did I make a wrong move?

In advance, thank you very much for your help.

**Comment by StavEW** [comment]
Hi,

From what I can remember, it was something to do with their .dll and .asmdef files not being configured for windows platform
Try setting the UWP platform setting on the "websocket-sharp" file (SDK - Any SDK, ScriptingBackend to IL2CPP,  Don't process - unchecked)
Also, try checking if the "Newtonsoft.Json" file has a WSA Player/Editor checked

Hope it helps,

Steve
________________________________
